# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: The Handbook
  product: The Handbook
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Introduction
    output: web, pdf
    folderitems:
    - title: Welcome
      url: /p1_landing_page.html
      output: web

  - title: Course Maintenance
    output: web, pdf

    folderitems:
    - title: Sample 4
      url: /p1_sample4.html
      output: web, pdf

    - title: Sample 5
      url: /p1_sample5.html
      output: web, pdf

    - title: Sample 6
      url: /p1_sample6.html
      output: web, pdf

    - title: Sample 7
      url: /p1_sample7.html
      output: web, pdf

  - title: Course Management
    output: web, pdf

    folderitems:
    - title: Sample 4
      url: /p1_sample4.html
      output: web, pdf

  - title: Additional Technologies
    output: web, pdf

    folderitems:
    - title: Sample 4
      url: /p1_sample4.html
      output: web, pdf

  - title: Appendix
    output: web, pdf
    
    folderitems:
    - title: Sample 4
      url: /p1_sample4.html
      output: web, pdf
  output: web, pdf
